[package]
name = "scanner"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>", "Milan Loveless <milan.loveless@gmail.com>", "Michael Matuzak <mmatuzak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ressa = "0.6.0"
resast = "0.3.0"